version: '3'

services:
  php:
    build: .
    ports:
      - '80:80'
    volumes:
      - './sample:/var/www/'
      - './vhost:/etc/apache2/sites-enabled:ro'
    links:
      - mysql

  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
